version: '3'
services:
  my_app:
    image: multiversecamp/sample_app:latest
    deploy:
      mode: global
  my_proxy:
    image: multiversecamp/proxy:latest
    deploy:
      mode: global
    environment:
      - APP_IP=my_app
    depends_on:
      - "my_app"
  my_nginx:
    image: nginx
    deploy:
      mode: global
    ports:
        - "80:80"
    volumes:
    - serve-pubkey:/usr/share/nginx/html:ro
  my_tendermint:
    image: multiversecamp/tendermint:latest
    ports:
      - "46656:46656"
      - "46657:46657"
    deploy:
      mode: global
    volumes:
    - /tmp:/tendermint
    - serve-pubkey:/pubkey
    environment:
      - VALIDATORS=
      - SEEDS=0.0.0.0
      - PROXY_IP=my_proxy
      - DATA_ROOT=/tendermint
    depends_on:
      - "my_proxy"
volumes:
  serve-pubkey:
  