version: '3'
services:
  my_app:
    image: multiversecamp/sample_app:rc
    deploy:
      mode: global
  my_proxy:
    image: multiversecamp/proxy:rc
    deploy:
      mode: global
    environment:
      - APP_IP=my_app
    depends_on:
      - "my_app"
  my_nginx:
    image: nginx
    deploy:
      mode: global
    ports:
        - "80:80"
    volumes:
    - serve-pubkey:/usr/share/nginx/html:ro
  my_tendermint:
    image: multiversecamp/tendermint:rc
    deploy:
      mode: global
    volumes:
    - /tmp:/tendermint
    - serve-pubkey:/pubkey
    environment:
      - VALIDATORS=192.168.99.100,192.168.99.101
      - SEEDS=192.168.99.100,192.168.99.101
      - PROXY_IP=my_proxy
      - DATA_ROOT=/tendermint
    depends_on:
      - "my_proxy"
volumes:
  serve-pubkey:
  