#!/bin/bash

NETWORK_NAME=testNet
# DOCKER_APP=./Dockerfile.sample_app
DOCKER_APP=./Dockerfile.app
DOCKER_PROXY=./Dockerfile.proxy
DOCKER_TENDERMINT=./Dockerfile.tendermint

rm Dockerfile.app
cp Dockerfile.app.template Dockerfile.app
echo "RUN go get -v ${1}/${2}/..." >> Dockerfile.app
echo "CMD [\"$2\"]" >> Dockerfile.app



# BUILD 

docker build -f $DOCKER_APP -t app:latest .
docker build -f $DOCKER_PROXY -t proxy:latest .
docker build -f $DOCKER_TENDERMINT -t tendermint:latest .

