#!/bin/bash

NETWORK_NAME=testNet
# DOCKER_APP=./Dockerfile.sample_app
DOCKER_APP=./Dockerfile.myapp
DOCKER_PROXY=./Dockerfile.proxy
DOCKER_TENDERMINT=./Dockerfile.tendermint

rm Dockerfile.myapp
touch Dockerfile.myapp
echo "FROM golang:1.8" >> Dockerfile.myapp
echo "RUN go get -v ${1}/${2}/..." >> Dockerfile.myapp
echo "EXPOSE 46659" >> Dockerfile.myapp
echo "CMD [\"$2\"]" >> Dockerfile.myapp



# BUILD 

docker build -f $DOCKER_APP -t app:latest .
docker build -f $DOCKER_PROXY -t proxy:latest .
docker build -f $DOCKER_TENDERMINT -t tendermint:latest .

