#!/bin/bash

NETWORK_NAME=testNet
DOCKER_APP=./Dockerfile.sample_app
DOCKER_PROXY=./Dockerfile.proxy
DOCKER_TENDERMINT=./Dockerfile.tendermint


# CLEAN

docker network rm $NETWORK_NAME
docker ps -a | grep -v 'CONTAINER' | awk '{print $1}' | xargs docker stop 
docker ps -a | grep -v 'CONTAINER' | awk '{print $1}' | xargs docker rm 

# docker images | grep -v 'REPOSITORY' | awk '{print $3}' | xargs docker rmi -f

