#!/bin/bash

SUFFIX=$1


SCREEN_NAME=screen$1
NETWORK_NAME=testNet$SUFFIX
TENDERMINT_DATA=tendermintData$SUFFIX

# CREATE NETWORK, VOLUME AND IMAGES

docker network create $NETWORK_NAME
docker volume create --name $TENDERMINT_DATA


echo "Launching app"
cmdApp="docker run -it --name app$SUFFIX --net=$NETWORK_NAME app; exec bash"
echo $cmdApp
screen -dmS app$SUFFIX bash -c "$cmdApp"


sleep 1
echo "Launching proxy"
cmdProxy="docker run -it --name proxy$SUFFIX --net=$NETWORK_NAME proxy abci_proxy -proxy=tcp://app$SUFFIX:46659; exec bash"
echo $cmdProxy
screen -dmS proxy$SUFFIX bash -c "$cmdProxy"


# screen -dmS test bash -c 'docker run -it --name proxy$SUFFIX --net=$NETWORK_NAME proxy /bin/bash; exec bash'
# docker run -it --name proxy --net=$NETWORK_NAME proxy
# docker run -it --name tendermint --net=$NETWORK_NAME tendermint

sleep 1
echo "Generating json file in data/pub_key.json"
docker run -it --rm --net=$NETWORK_NAME --volume=$TENDERMINT_DATA:/tendermint tendermint gen_validator | python -c '
import json, sys
tbl=json.load(sys.stdin)
for t in tbl:
   if t == "pub_key":
      print tbl[t];
' > data/pub_key.json


sleep 1
echo "Launching tendermint --- "
docker run -it --net=$NETWORK_NAME --volume=$TENDERMINT_DATA:/tendermint tendermint init
cmdTendermint="docker run -it --net=$NETWORK_NAME --volume=$TENDERMINT_DATA:/tendermint tendermint node --proxy_app=tcp://proxy$SUFFIX:46658; exec bash"
echo $cmdTendermint
screen -dmS tendermint$SUFFIX bash -c "$cmdTendermint"
