#!/bin/bash

CHAIN_ID=$1
SUFFIX=$2
PROXY_PORT=$3
APP_PORT=$4

SCREEN_NAME=screen$1

NETWORK_NAME=$CHAIN_ID$SUFFIX
TENDERMINT_DATA=${CHAIN_ID}$SUFFIX



# CREATE NETWORK, VOLUME AND IMAGES

docker network create $NETWORK_NAME
docker volume create --name $TENDERMINT_DATA


echo "Launching app"
cmdApp="docker run -p $APP_PORT:$APP_PORT -it --name app$CHAIN_ID$SUFFIX --net=$NETWORK_NAME app; exec bash"
#echo $cmdApp
screen -dmS app$CHAIN_ID$SUFFIX bash -c "$cmdApp"

echo "Launching proxy"
cmdProxy="docker run -p $PROXY_PORT:46659 -it --name proxy$CHAIN_ID$SUFFIX --net=$NETWORK_NAME proxy abci_proxy -proxy=tcp://app$CHAIN_ID$SUFFIX:46659 -v; exec bash"
#echo $cmdProxy
screen -dmS proxy$CHAIN_ID$SUFFIX bash -c "$cmdProxy"

echo "Init tendermint"
docker run -it --rm --net=$NETWORK_NAME --volume=$TENDERMINT_DATA:/tendermint tendermint tendermint --home=/tendermint init 

