#!/bin/bash

CHAIN_ID=$1
PUB_KEYS=$2
TYPE='ed25519'

XAUTH="hQtMsgzwqpKYFwAwHN7leKRSdrzDgK1o"

url="http://ec2-54-172-87-22.compute-1.amazonaws.com:8080"

full_url="$url/addPublicKey?project=$CHAIN_ID&key=$PUB_KEYS"

URL=${full_url%$'\r'}

curl $URL
# -H "X-Authy-API-Key: $XAUTH")

