#!/bin/bash
PORT=46656
p2pseeds=
scriptPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


for M in "${@:2}"
do
       	#volumePath=`docker volume inspect $1$M | grep 'Mountpoint' | awk -F ':' '{print $2}' | awk -F '"' '{print $2}'`
        TENDERMINT_DATA=$1$M
        volumePath=/home/ec2-user/deployment/docker/volumes/$TENDERMINT_DATA
        find $volumePath/config.toml | xargs perl -pi -e "s/proxy_app.*/proxy_app = \"tcp:\/\/proxy$1$M:46658\"/g"
done

